[package]
name = "color-db"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio"] }
sqlxinsert = "0.11.0"
tokio = { version = "1.40.0", features = ["macros"] }
